export * from './page1/page1';
export * from './page2/page2';
export * from './my-teams/my-teams';
export * from './team-detail/team-detail';
export * from './teams/teams';
export * from './tournaments/tournaments';
export * from './game/game';
export * from './standings/standings';
export * from './team-home/team-home';